### PR TITLE
Make it clear for the next user

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @xster

**Comment by sethladd** [comment]
cc @hterkelsen for review

**Comment by zoechi** [comment]
some information about the upcoming DI package would be great ;-)

**Comment by hterkelsen** [comment]
lgtm but I don't have merge rights

**Comment by passsy** [comment]
Push. I wasted a few hours integrating `di` in my flutter app to find out it doesn't work.

**Comment by hterkelsen** [comment]
@matanlurey for review

**Comment by matanlurey** [comment]
@kevmoo needs to merge this.

**Comment by pavelgj** [comment]
The wording in this change is not accurate. DI has a transformer that generates a "static" (no mirrors) injector... that injector by itself is not great, but it doesn't use mirrors.

**Pull request merged**
